"""
Headless reporter HITL bridge for @runtime.

This mirrors the core logic in the FastAPI swarmworker HITL bridge:
- outbound: clarification requests -> publish `clarification_requested` to
  the normal devsper SSE sink via `event_sink.on_devsper_event(...)`
- inbound: user answers from Redis pubsub channel `devsper:inputs:{run_id}`
  -> inject answers into the active executor.
"""

from __future__ import annotations

import json
import logging
import queue
import threading
import time
from datetime import datetime
from typing import Any

from devsper.events import ClarificationResponse

logger = logging.getLogger(__name__)


def hitl_bridge_thread(
    redis_client: Any,
    run_id: str,
    clarification_queue: queue.Queue,
    swarm_ref: Any,
    stop_event: threading.Event,
    event_sink: Any,
) -> None:
    """
    Bridges requests from swarm/agent to Redis and answers back into the swarm.

    Preconditions:
    - `clarification_queue` is created and attached to the Swarm executor.
    - `event_sink` is the same object used by EventLog platform forwarding
      (so it has DAG enrichment state when publishing clarification events).
    """

    pubsub = redis_client.pubsub()
    input_channel = f"devsper:inputs:{run_id}"
    pubsub.subscribe(input_channel)

    # Prevent tight loops in the idle case.
    idle_sleep_s = 0.05

    while not stop_event.is_set():
        # 1) Outbound: take requests generated by the executor and publish for UI.
        try:
            req = clarification_queue.get_nowait()
        except queue.Empty:
            req = None

        if req is not None:
            try:
                # Create a minimal FakeEvent that the SSE sink understands.
                class FakeType:
                    value = "clarification_requested"

                class FakeEvent:
                    type = FakeType()
                    timestamp = datetime.now()
                    payload = req.to_dict() if hasattr(req, "to_dict") else {}

                event_sink.on_devsper_event(FakeEvent())
                logger.info(
                    "Published clarification request %s for run %s",
                    getattr(req, "request_id", "?"),
                    run_id,
                )
            except Exception:
                logger.exception("Failed publishing HITL clarification event")

        # 2) Inbound: wait for a user answer from the platform/CLI.
        # `get_message(..., timeout=...)` returns quickly so we can honor stop_event.
        try:
            msg = pubsub.get_message(ignore_subscribe_messages=True, timeout=0.1)
        except Exception:
            msg = None

        if msg and msg.get("type") == "message":
            try:
                data = json.loads(msg.get("data") or "{}")
                req_id = (data.get("request_id") or "").strip()
                answers = data.get("answers") or {}
                skipped = bool(data.get("skipped", False))

                if req_id and swarm_ref and getattr(swarm_ref, "_current_executor", None):
                    resp = ClarificationResponse(
                        request_id=req_id, answers=answers, skipped=skipped
                    )
                    swarm_ref._current_executor.receive_clarification(resp)
                    logger.info(
                        "Received HITL answer for %s (skipped=%s)", req_id, skipped
                    )
            except Exception:
                logger.exception("Failed processing HITL input message")

        if idle_sleep_s:
            time.sleep(idle_sleep_s)

