"""Advanced research tools: literature review, similarity, gaps, methodology, citations."""

from devsper.tools.research_advanced.literature_review_generator import LiteratureReviewGeneratorTool
from devsper.tools.research_advanced.paper_similarity_search import PaperSimilaritySearchTool
from devsper.tools.research_advanced.research_gap_finder import ResearchGapFinderTool
from devsper.tools.research_advanced.methodology_extractor import MethodologyExtractorTool
from devsper.tools.research_advanced.paper_contribution_extractor import PaperContributionExtractorTool
from devsper.tools.research_advanced.paper_dataset_identifier import PaperDatasetIdentifierTool
from devsper.tools.research_advanced.citation_context_extractor import CitationContextExtractorTool
from devsper.tools.research_advanced.research_topic_mapper import ResearchTopicMapperTool
from devsper.tools.research_advanced.paper_trend_analyzer import PaperTrendAnalyzerTool
from devsper.tools.research_advanced.paper_method_comparator import PaperMethodComparatorTool
from devsper.tools.research_advanced.parallel_document_analyzer import ParallelDocumentAnalyzerTool
from devsper.tools.research_advanced.swarm_literature_review import SwarmLiteratureReviewTool
